---
# Playbook to create the logical toplogy of ACI
#

- name: ACI logical topology
  vars_files:
    - ~/.vars-aci-credentials.yml
#    - "{{ varfile }}"
  hosts: all

  connection: local
  gather_facts: no

  vars:
    base_dir: "../data-logical-topology/output-files/"

  tasks:
  #
  # list of tenants
  #
  - name: Get a list of tenants from ACI
    aci_tenant:
      state=query
      hostname="{{ inventory_hostname }}"
      username="{{ apic_user }}"
      password="{{ apic_pass }}"
      use_proxy=no
      validate_certs=no
    no_log: true
    register: out

  #
  # Write tenant information to a file for processing later
  #
  - copy: content="{{ out.existing }}" dest={{ base_dir }}{{ [group_names][0][0] }}/tenants-output.json

  #
  # list of VRFs
  #
  - name: Get a list of VRFs from ACI
    aci_vrf:
      state=query
      hostname="{{ inventory_hostname }}"
      username="{{ apic_user }}"
      password="{{ apic_pass }}"
      use_proxy=no
      validate_certs=no
    no_log: true
    register: out

  #
  # Write VRF information to a file for processing later
  #
  - copy: content="{{ out.existing }}" dest={{ base_dir }}{{ [group_names][0][0] }}/vrfs-output.json

  #
  # list of BDs
  #
  - name: Get a list of BDs from ACI, use modified aci_bd_feld09 module to include subnet information
    aci_bd_feld09:
      state=query
      hostname="{{ inventory_hostname }}"
      username="{{ apic_user }}"
      password="{{ apic_pass }}"
      use_proxy=no
      validate_certs=no
    no_log: true
    register: out

  #
  # Write BD information to a file for processing later
  #
  - copy: content="{{ out.existing }}" dest={{ base_dir }}{{ [group_names][0][0] }}/bds-output.json
    
  #
  # list of APs
  #
  - name: Get a list of APs from ACI
    aci_ap:
      state=query
      hostname="{{ inventory_hostname }}"
      username="{{ apic_user }}"
      password="{{ apic_pass }}"
      use_proxy=no
      validate_certs=no
    no_log: true
    register: out

  #
  # Write AP information to a file for processing later
  #
  - copy: content="{{ out.existing }}" dest={{ base_dir }}{{ [group_names][0][0] }}/aps-output.json

  #
  # list of EPGs
  #
  - name: Get a list of EPGs from ACI, use modified aci_epg_feld09 module to get a list of static ports
    aci_epg_feld09:
      state=query
      hostname="{{ inventory_hostname }}"
      username="{{ apic_user }}"
      password="{{ apic_pass }}"
      use_proxy=no
      validate_certs=no
    no_log: true
    register: out

  #
  # Write EPG information to a file for processing later
  #
  - copy: content="{{ out.existing }}" dest={{ base_dir }}{{ [group_names][0][0] }}/epgs-output.json

  #
  # list of Provider Contracts
  #
  - name: Get a list of Provider Contracts from ACI
    aci_epg_to_contract:
      state=query
      contract_type=provider
      hostname="{{ inventory_hostname }}"
      username="{{ apic_user }}"
      password="{{ apic_pass }}"
      use_proxy=no
      validate_certs=no
    # no_log: true
    register: out

  #
  # Write provider contract information to a file for processing later
  #
  - copy: content="{{ out.existing }}" dest={{ base_dir }}{{ [group_names][0][0] }}/provider-contracts-output.json

  #
  # list of Consumer Contracts
  #
  - name: Get a list of Consumer Contracts from ACI
    aci_epg_to_contract:
      state=query
      contract_type=consumer
      hostname="{{ inventory_hostname }}"
      username="{{ apic_user }}"
      password="{{ apic_pass }}"
      use_proxy=no
      validate_certs=no
    # no_log: true
    register: out

  #
  # Write consumer contract information to a file for processing later
  #
  - copy: content="{{ out.existing }}" dest={{ base_dir }}{{ [group_names][0][0] }}/consumer-contracts-output.json

# This is the end, my friend
...
